#!/usr/bin/env python3
"""Generate the CivilComments-WILDS + Gemma-2-27B budget-ladder (v2) experiment.

Motivation (2026-07-07). The 500k_v1 run produced a held-out ~0.69 across all
three methods because the *few-shot accuracy engine never ran*: the 500k budget
died in the initial population (fairness audit alone was ~38% of it), so the
surviving front was 0-shot terse prompts. MO-CAPO's own paper reaches 0.87-0.93
on binary classification (Subj) precisely via few-shot + evolved instructions at
a 7.5M-token budget. This generator rebuilds the CivilComments experiment with
paper-faithful knobs and a budget ladder (1M -> 5M -> 10M) so we can see where
Gemma actually lands.

It transforms the frozen ``*_500k_v1_gemma_*`` config + pipeline files by:

  1. tag-substitution ``500k_v1`` -> ``<rung>_v2`` (rewrites every output_dir,
     portfolio path, experiment_name and run tag, so rungs never collide), and
  2. targeted line-edits of the search knobs ONLY (comments/paths preserved):

       block_size ...................... 56 -> 30   (300/30 = 10 blocks; finer
                                                      racing => more candidates
                                                      admitted, matches paper)
       few_shot.max_few_shot_examples ..  3 ->  5   (paper k_max = 5; the primary
                                                      accuracy lever)
       few_shot.few_shot_probability ... 0.3 -> 0.5 (explore the few-shot arm more)
       fairness.eval_pairs ............. 80 -> 40   (Phase 2: halve the in-loop
                                                      audit so it stops starving
                                                      exploration; kept in-loop
                                                      for EVERY candidate, so the
                                                      FairCAPO steering story is
                                                      intact -- the reported
                                                      fairness is still the
                                                      held-out 1000-example gap)
       intensification.max_blocks_per_challenger  5 -> 8  (allow deeper racing
                                                      now that there are 10 blocks)
       budget.max_budget ............... 500000 -> <rung>

The held-out eval stays at test_size 1000 and is untouched except for tags.
BIOS and the frozen 500k_v1 CivilComments files are NOT modified.

Run from the repo root:

    PYTHONPATH=. python scripts/hpc/gen_civilcomments_budget_ladder.py

Writes configs to configs/HPC_Config/ and pipeline/build scripts to scripts/hpc/.
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CONFIG_DIR = REPO / "configs" / "HPC_Config"
HPC_DIR = REPO / "scripts" / "hpc"

# rung tag -> max_budget (float). Tags use the same "k" unit as the frozen
# 500k_v1 family (1000k/5000k/7500k) so filenames read consistently. The top
# rung is the paper's own 7.5M-token budget (Table 3 reaches 0.87-0.93 on binary
# classification there); 10M was dropped in favour of matching the paper.
RUNGS: dict[str, float] = {
    "1000k": 1_000_000.0,
    "5000k": 5_000_000.0,
    "7500k": 7_500_000.0,
}

# Config files that carry the evolutionary SEARCH knobs (get the line-edits).
SEARCH_CONFIGS = (
    "civilcomments_faircapo_500k_v1_gemma_HPC.yaml",
    "civilcomments_ablation_500k_v1_gemma_HPC.yaml",
    "civilcomments_nsga2po_500k_v1_gemma_HPC.yaml",
)

# Config files that only need tag-substitution (eval / table / aggregate).
PASSTHROUGH_CONFIGS = (
    "civilcomments_eval_large_500k_v1_gemma_HPC.yaml",
    "civilcomments_eval_ablation_large_500k_v1_gemma_HPC.yaml",
    "civilcomments_eval_nsga_large_500k_v1_gemma_HPC.yaml",
    "civilcomments_experiment_table_500k_v1_gemma_large_HPC.yaml",
    "civilcomments_aggregate_500k_v1_gemma_large_HPC.yaml",
)

# Shell scripts. The original 500k_v1 pipeline scripts were DELETED (that run
# failed), so the generator is self-hosting: it uses the committed 1000k_v2
# scripts as templates and substitutes the rung tag. Regenerating the 1000k
# rung reproduces the template verbatim; 5000k/7500k just swap the rung.
SHELL_TEMPLATE_RUNG = "1000k"
SHELL_SCRIPTS = (
    "submit_civilcomments_{rung}_v2_gemma_pipeline.sh",
    "build_civilcomments_{rung}_v2_gemma_large_outputs.sh",
)

PROVENANCE = (
    "# GENERATED by scripts/hpc/gen_civilcomments_budget_ladder.py -- do not\n"
    "# hand-edit; change the generator and re-run. Derived from the frozen\n"
    "# {src} with paper-faithful v2 knobs (block_size 30, k_max 5,\n"
    "# few_shot_probability 0.5, eval_pairs 40, max_blocks 8) at the {rung}\n"
    "# token budget. See the generator docstring for the full rationale.\n"
)


def _apply_search_knobs(text: str, budget: float) -> str:
    """Line-edit the evolutionary search knobs, leaving everything else intact.

    Each substitution is anchored to the key's exact indentation so it matches
    at most one line and is a no-op when the key is absent (e.g. the fairness-off
    ablation has no ``eval_pairs``; NSGA has no ``block_size``).
    """
    edits = (
        (r"(?m)^block_size:[ \t]*.*$", "block_size: 30"),
        (r"(?m)^  max_few_shot_examples:[ \t]*.*$", "  max_few_shot_examples: 5"),
        (r"(?m)^  few_shot_probability:[ \t]*.*$", "  few_shot_probability: 0.5"),
        (r"(?m)^  eval_pairs:[ \t]*.*$", "  eval_pairs: 40"),
        (
            r"(?m)^  max_blocks_per_challenger:[ \t]*.*$",
            "  max_blocks_per_challenger: 8",
        ),
        (r"(?m)^  max_budget:[ \t]*.*$", f"  max_budget: {budget}"),
    )
    for pattern, replacement in edits:
        text = re.sub(pattern, replacement, text)
    return text


def _retag(text: str, rung: str) -> str:
    """Rewrite the run tag ``500k_v1`` -> ``<rung>_v2`` everywhere.

    Also rewrites the human-readable ``500k v1`` display strings (echo lines /
    comments, space instead of underscore) so submit-log messages don't
    misleadingly announce a "500k v1" run when a ladder rung is submitted.
    """
    text = text.replace("500k_v1", f"{rung}_v2")
    text = text.replace("500k v1", f"{rung} v2")
    text = text.replace("500k budget", f"{rung} v2 budget")
    # Bare "v1 search" in the flow-diagram comment (no 500k prefix).
    text = text.replace("v1 search", "v2 search")
    return text


def _out_name(src_name: str, rung: str) -> str:
    return src_name.replace("500k_v1", f"{rung}_v2")


def _write(path: Path, text: str) -> None:
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(f"  wrote {path.relative_to(REPO)}")


def generate() -> None:
    for rung, budget in RUNGS.items():
        print(f"[{rung}_v2] budget={budget:,.0f}")

        for name in SEARCH_CONFIGS:
            src = CONFIG_DIR / name
            text = _retag(src.read_text(encoding="utf-8"), rung)
            text = _apply_search_knobs(text, budget)
            header = PROVENANCE.format(src=name, rung=f"{rung}_v2")
            _write(CONFIG_DIR / _out_name(name, rung), header + text)

        for name in PASSTHROUGH_CONFIGS:
            src = CONFIG_DIR / name
            text = _retag(src.read_text(encoding="utf-8"), rung)
            header = PROVENANCE.format(src=name, rung=f"{rung}_v2")
            _write(CONFIG_DIR / _out_name(name, rung), header + text)

        for tmpl in SHELL_SCRIPTS:
            src_name = tmpl.format(rung=SHELL_TEMPLATE_RUNG)
            out_name = tmpl.format(rung=rung)
            text = (HPC_DIR / src_name).read_text(encoding="utf-8")
            if rung != SHELL_TEMPLATE_RUNG:
                # Template is already the 1000k_v2 script: swap its rung tag
                # (both the "1000k_v2" paths and the "cc1000k-" job-name prefix).
                text = text.replace(f"{SHELL_TEMPLATE_RUNG}_v2", f"{rung}_v2")
                text = text.replace(f"{SHELL_TEMPLATE_RUNG} v2", f"{rung} v2")
                text = text.replace(
                    f"--job-name=cc{SHELL_TEMPLATE_RUNG}-", f"--job-name=cc{rung}-"
                )
            _write(HPC_DIR / out_name, text)


if __name__ == "__main__":
    generate()
